# Generated by Django 4.2.2 on 2023-06-25 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_api.validations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='excel_files/', validators=[user_api.validations.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_api_excelfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
