# Generated by Django 4.1.5 on 2023-07-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_excelfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='user',
        ),
    ]
