# Generated by Django 4.1.5 on 2023-07-03 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_remove_appuser_is_staff_remove_excelfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_api_excelfiles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
