# Generated by Django 4.1.5 on 2023-07-08 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_alter_excelfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='excel_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])]),
        ),
    ]
